version: 2.1

jobs:
  build:
    working_directory: ~/wanikani-minder
    docker:
      - image: circleci/clojure:lein-2.7.1
    environment:
      JVM_OPTS: -Xmx3200m # limit the maximum heap size to prevent out of memory errors
      LEIN_ROOT: "true"
    steps:
      - checkout
      - restore_cache:
          key: cci-demo-clojure-{{ checksum "project.clj" }}
      - run: lein deps
      - save_cache:
          paths:
            - ~/.m2
          key: cci-demo-clojure-{{ checksum "project.clj" }}
      - run: lein test